// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wasta.CareerCoach.Data;

#nullable disable

namespace Wasta.CareerCoach.Data.Migrations
{
    [DbContext(typeof(CoachDbContext))]
    partial class CoachDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wasta.CareerCoach.Domain.StudentCoachPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Assessment")
                        .HasColumnType("text");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<int>("AttemptId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Headline")
                        .HasColumnType("text");

                    b.Property<string>("InterviewLine")
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProjectDesc")
                        .HasColumnType("text");

                    b.Property<string>("ProjectSkillsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ProjectSkills");

                    b.Property<string>("ProjectTitle")
                        .HasColumnType("text");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ProviderUsed")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ScoreId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("WeeklyPlanJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("WeeklyPlan");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .IsUnique();

                    b.HasIndex("StudentId", "Status");

                    b.ToTable("StudentCoachPlans", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
