CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112631_InitialCreate') THEN
    CREATE TABLE "StudentCoachPlans" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StudentId" integer NOT NULL,
        "AttemptId" integer NOT NULL,
        "ScoreId" integer NOT NULL,
        "Status" character varying(12) NOT NULL,
        "Headline" text,
        "Assessment" text,
        "WeeklyPlan" jsonb,
        "ProjectTitle" text,
        "ProjectDesc" text,
        "ProjectSkills" jsonb,
        "InterviewLine" text,
        "PromptVersion" character varying(10) NOT NULL,
        "ProviderUsed" character varying(30),
        "AttemptCount" integer NOT NULL,
        "LastError" character varying(500),
        "GeneratedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_StudentCoachPlans" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112631_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_StudentCoachPlans_AttemptId" ON "StudentCoachPlans" ("AttemptId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112631_InitialCreate') THEN
    CREATE INDEX "IX_StudentCoachPlans_StudentId_Status" ON "StudentCoachPlans" ("StudentId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801112631_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260801112631_InitialCreate', '10.0.4');
    END IF;
END $EF$;
COMMIT;

