CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801190604_InitialCreate') THEN
    CREATE TABLE "ChatSessions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PublicId" uuid NOT NULL,
        "StudentId" integer,
        "VisitorId" character varying(64),
        "MessageCount" integer NOT NULL,
        "LastMessageAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ChatSessions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801190604_InitialCreate') THEN
    CREATE TABLE "ChatMessages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SessionId" integer NOT NULL,
        "Role" character varying(16) NOT NULL,
        "Content" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ChatMessages_ChatSessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES "ChatSessions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801190604_InitialCreate') THEN
    CREATE INDEX "IX_ChatMessages_SessionId_CreatedAt" ON "ChatMessages" ("SessionId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801190604_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ChatSessions_PublicId" ON "ChatSessions" ("PublicId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801190604_InitialCreate') THEN
    CREATE INDEX "IX_ChatSessions_StudentId" ON "ChatSessions" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801190604_InitialCreate') THEN
    CREATE INDEX "IX_ChatSessions_VisitorId" ON "ChatSessions" ("VisitorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260801190604_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260801190604_InitialCreate', '10.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803223303_AddStudentIdToChatMessage') THEN
    ALTER TABLE "ChatMessages" ADD "StudentId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803223303_AddStudentIdToChatMessage') THEN
    CREATE INDEX "IX_ChatMessages_StudentId_CreatedAt" ON "ChatMessages" ("StudentId", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260803223303_AddStudentIdToChatMessage') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260803223303_AddStudentIdToChatMessage', '10.0.4');
    END IF;
END $EF$;
COMMIT;

