using System.Text.Json;
using Wasta.Ai;

namespace Wasta.DevHost.Adapters;

/// <summary>
/// A stub AI provider so the whole system runs end to end with NO API keys.
/// It returns fixed, hand-written fixtures - it is not a model and does not
/// reason about the input.
///
/// It sits LAST in the configured chain, and the chain skips providers whose
/// IsConfigured is false, so the moment a real Groq or Gemini key is present
/// that provider serves instead and this one is never reached. That makes it
/// a development convenience, not a silent fallback that could mask a
/// misconfigured production deployment.
///
/// Its replies are deliberately written to satisfy CoachResponseValidator,
/// which is itself a useful check: if the validator's rules change and this
/// fixture stops passing, the dev host surfaces it immediately.
/// </summary>
public class DevEchoProvider : IAiProvider
{
    public string Name => "dev";

    public bool IsConfigured => true;

    public Task<string> CompleteAsync(string systemPrompt, IReadOnlyList<AiChatTurn> turns, AiCallOptions? callOptions, CancellationToken ct)
    {
        var isCareerCoach = systemPrompt.Contains("technical mentor", StringComparison.OrdinalIgnoreCase);
        var lastUserMessage = turns.LastOrDefault()?.Content ?? string.Empty;

        return Task.FromResult(isCareerCoach
            ? CoachPlanFixture()
            : ChatReplyFixture(systemPrompt, lastUserMessage));
    }

    private static string CoachPlanFixture()
    {
        var payload = new
        {
            status = "ok",
            version = "1.0",
            data = new
            {
                headline = "Close the gap between statistics and data pipelines",
                assessment =
                    "Your data handling is ahead of your statistics work, and that gap shows up as soon as a model " +
                    "needs explaining rather than just running. Applied modelling sits in between: you can produce a " +
                    "result, but justifying the choice behind it is harder. Data pipelines are the weakest area, which " +
                    "matters most once the data lives in a database rather than a clean notebook file on your laptop.",
                weekly_plan = new object[]
                {
                    new
                    {
                        week = 1,
                        focus = "Statistics fundamentals",
                        actions = new[] { "Review probability distributions", "Work through hypothesis testing exercises" },
                        checkpoint = "You can explain a p-value from memory.",
                    },
                    new
                    {
                        week = 2,
                        focus = "Joins and aggregation",
                        actions = new[] { "Write JOIN queries across three tables", "Practise GROUP BY with HAVING clauses" },
                        checkpoint = "You can join and aggregate without checking syntax.",
                    },
                    new
                    {
                        week = 3,
                        focus = "Model evaluation",
                        actions = new[] { "Compare models with cross-validation", "Read about the bias and variance tradeoff", "Rebuild one earlier project with proper evaluation" },
                        checkpoint = "You can defend a model choice using one metric.",
                    },
                    new
                    {
                        week = 4,
                        focus = "Work outside notebooks",
                        actions = new[] { "Move one analysis into a reusable function", "Add a small test for that function" },
                        checkpoint = "The analysis runs without manual notebook steps.",
                    },
                },
                project_suggestion = new
                {
                    title = "Churn predictor with a SQL backend",
                    description =
                        "Build a small churn predictor that pulls its training data through SQL joins across at least " +
                        "three tables instead of a flat CSV, then evaluate it with cross-validation. This targets the " +
                        "pipeline and evaluation gaps together, and it is not something either of your listed projects " +
                        "already covers.",
                    skills_practised = new[] { "SQL", "cross-validation", "feature engineering" },
                },
                interview_line =
                    "I build models quickly, and I am now working through the statistics that explain why they behave the way they do.",
            },
            warnings = new[] { "Generated by the DevEchoProvider fixture, not a real model." },
        };

        return JsonSerializer.Serialize(payload);
    }

    private static string ChatReplyFixture(string systemPrompt, string userMessage)
    {
        var asksAboutJobs = userMessage.Contains("job", StringComparison.OrdinalIgnoreCase)
            || userMessage.Contains("role", StringComparison.OrdinalIgnoreCase)
            || userMessage.Contains("opportunit", StringComparison.OrdinalIgnoreCase);

        if (asksAboutJobs && systemPrompt.Contains("OPEN_OPPORTUNITIES", StringComparison.Ordinal))
        {
            // Echo back the titles the host actually supplied, so the demo
            // shows the listings really did reach the prompt. Anchor on the
            // LAST occurrence of the marker: the rules section near the top
            // of the prompt also names OPEN_OPPORTUNITIES, and matching that
            // one would sweep up the knowledge base's bullets instead.
            var marker = systemPrompt.LastIndexOf("OPEN_OPPORTUNITIES:", StringComparison.Ordinal);
            var titles = marker < 0
                ? []
                : systemPrompt[marker..]
                    .Split('\n')
                    .Where(l => l.StartsWith("- ", StringComparison.Ordinal))
                    .Select(l => l[2..].Split(". Link:")[0])
                    .ToList();

            return titles.Count == 0
                ? "I don't have any open roles listed at the moment."
                : "[dev fixture] Here is what is currently open:\n" + string.Join("\n", titles.Select(t => "- " + t));
        }

        if (userMessage.Contains("my score", StringComparison.OrdinalIgnoreCase)
            || userMessage.Contains("my account", StringComparison.OrdinalIgnoreCase))
        {
            return "[dev fixture] I cannot see account-specific information such as your score. "
                + "You can find it on your results page, or contact support if something looks wrong.";
        }

        return "[dev fixture] This is a stub reply from DevEchoProvider - no AI key is configured. "
            + "Add a Groq or Gemini key and this provider is skipped automatically.";
    }
}
